### PR TITLE
Ignore struct fields with `inline` tag flag

### LINKED ISSUE #8: tagliatelle now warns on inline struct fields
Since 7b219253661560e60d284e3cddfb912dc49862fc, structs with `json:",inline"` fields now prompt a warning from tagliatelle that a name should be given in the expected camelCase.

I think this is incorrect behavior as there is no field name for an `inline` struct.

### PR DESCRIPTION
**Pull request by silverlyra**
Fixes #8.

Updated the test file to include a `json:",inline"` field. Without the fix, that file fails with:

```
=== RUN   TestAnalyzer
    analysistest.go:446: a/sample.go:10:14: unexpected diagnostic: json(camel): got 'Quux' want 'quux'
```

### CODE REVIEW

File: tagliatelle.go [hunk 1]
```diff
@@ -95,6 +95,10 @@ func analyze(pass *analysis.Pass, config Config, n *ast.StructType, field *ast.F
 			// skip when skipped :)
 			continue
 		}
+		if hasTagFlag(flags, "inline") {
```
Comment (ldez) [inline tagliatelle.go:98]:
```suggestion

		if hasTagFlag(flags, "inline") && len(field.Names) == 0 {
```

**Review by ldez — CHANGES_REQUESTED** [review]

**Comment by ldez** [comment]
> analysistest.go:446: a/sample.go:10:14: unexpected diagnostic: json(camel): got 'Quux' want 'quux'

This is the expected behavior as you can see [here](https://github.com/ldez/tagliatelle/issues/8#issuecomment-1021661926)

**Comment by ldez** [comment]
:thinking: the yaml parser doesn't have the same behavior as json with inline.

**Review by ldez — APPROVED** [review]
I will merge PR in the current state, but I will change the behavior in the next commit.
Because ``Quux Quux `json:",inline"` `` must fail.

**Comment by ldez** [comment]
In fact, I cannot change the behavior because yaml parser is able to read `json` tags...

I'm not happy with the current solution but, for now, I don't see any good solution.
